#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
if ! source $SCRIPT_DIR/functions.sh; then
    echo "ERROR: Missing functions file."
    exit 1
fi
if [[ ! $(whoami) == "root" ]]; then
    error "You need to be root in order to run sanei."
    exit 1
fi

case ${ARGUMENTS[0]} in
    "install" )
        sanei_install "${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}"
        ;;
    "update" )
        sanei_update "${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}"
        ;;
    "updateall" )
        sanei_updateall
        ;;
    "override" )
        sanei_override
        ;;
    "setinstalled" )
        set_installed ${ARGUMENTS[1]}
        ;;
    "showconfig" )
        print_config
        ;;
    "list" )
        sanei_list_modules_with_status
        ;;
    "module" )
        if [[ ${ARGUMENTS[1]} && -f $SCRIPT_DIR/modules/${ARGUMENTS[1]}/${ARGUMENTS[2]}.sh ]]; then
            source $SCRIPT_DIR/modules/${ARGUMENTS[1]}/${ARGUMENTS[2]}.sh "${ARGUMENTS[@]:3:${#ARGUMENTS[@]}}"
        else
            error "No operation ${ARGUMENTS[2]} for module ${ARGUMENTS[1]}."
        fi
        ;;
    "lxc" )
        case ${ARGUMENTS[1]} in
            "create" )
                REINSTALL=true
                __SPECIAL=true
                sanei_install lxc-template "${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}"
                ;;
            "updateall" )
                sanei_updateall_containers
                ;;
            * )
                echo "Available commands are:"
                echo "  lxc updateall"
                echo "  lxc create TEMPLATE_NAME"
                ;;
        esac
        ;;
    # NOT IMPLEMENTED YET:
    "overridelxc" )
        exit 0;
        sanei_overridelxc
        ;;
    "configure" )
        exit 0;
        sanei_configure
        ;;
    * )
        echo "Welcome to SANEi 0.9"
        echo
        echo "Available commands are:"
        echo "  install"
        echo "  update [MODULE]"
        echo "  updateall"
        echo "  override"
        echo "  list"
        echo "  module [MODULE] [OPERATION]"
        echo "  lxc updateall"
        echo "  lxc create [TEMPLATE_NAME]"
        ;;
esac
