#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
if ! source $SCRIPT_DIR/functions.sh; then
    echo "ERROR: Missing functions file."
    exit 1
fi
if [[ ! $(whoami) == "root" ]]; then
    error "You need to be ${LIGHTRED}root${RESET} in order to run sanei."
    exit 1
fi

case ${ARGUMENTS[0]} in
    "install" )
        sanei_install "${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}"
        ;;
    "update" )
        sanei_update "${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}"
        ;;
    "updateall" )
        sanei_updateall
        ;;
    "override" )
        sanei_override
        ;;
    "setinstalled" )
        set_installed ${ARGUMENTS[1]}
        ;;
    "config" )
        case ${ARGUMENTS[1]} in
            "list" )
                print_config | sort
                ;;
            "set" )
                if [[ ! -z ${ARGUMENTS[2]} ]]; then
                    store_shared_config ${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}
                fi
                ;;
            "setlocal" )
                if [[ ! -z ${ARGUMENTS[2]} ]]; then
                    store_local_config ${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}
                fi
                ;;
            * )
                echo "Available commands are:"
                echo "  config list"
                echo "  config set [VAR] [VALUE]"
                echo "  config setlocal [VAR] [VALUE]"
                ;;
        esac
        ;;
    "list" )
        sanei_list_modules_with_status
        ;;
    "module" )
        if [[ ${ARGUMENTS[1]} && -d $SCRIPT_DIR/modules/${ARGUMENTS[1]} ]]; then
            if [[ -f $SCRIPT_DIR/modules/${ARGUMENTS[1]}/${ARGUMENTS[2]}.sh ]]; then
                MODULE_DIR=$SCRIPT_DIR/modules/${ARGUMENTS[1]}
                source $SCRIPT_DIR/modules/${ARGUMENTS[1]}/${ARGUMENTS[2]}.sh "${ARGUMENTS[@]:3:${#ARGUMENTS[@]}}" ""
            else
                if [[ ${ARGUMENTS[2]} ]]; then
                    error "No operation ${ARGUMENTS[2]} for module ${ARGUMENTS[1]}."
                fi
                echo "Available commands are:"
                list_files $SCRIPT_DIR/modules/${ARGUMENTS[1]} | sed s/.sh$// | sed "s/^/  /"
            fi
        fi
        ;;
    "lxc" )
        case ${ARGUMENTS[1]} in
            "create" )
                REINSTALL=true
                __SPECIAL=true
                sanei_install lxc-template "${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}"
                ;;
            "updateall" )
                sanei_updateall_containers
                ;;
            * )
                echo "Available commands are:"
                echo "  lxc updateall"
                echo "  lxc create TEMPLATE_NAME"
                ;;
        esac
        ;;
    # NOT IMPLEMENTED YET:
    "overridelxc" )
        todo "override lxc"
        exit 0;
        sanei_overridelxc
        ;;
    "configure" )
        todo "changing configuration"
        exit 0;
        sanei_configure
        ;;
    * )
        echo "Welcome to SANEi 0.9"
        echo
        echo "Available commands are:"
        echo "  install"
        echo "  update [MODULE]"
        echo "  updateall"
        echo "  override"
        echo "  list"
        echo "  config list"
        echo "  config set [VAR] [VALUE]"
        echo "  config setlocal [VAR] [VALUE]"
        echo "  module [MODULE] [OPERATION]"
        echo "  lxc updateall"
        echo "  lxc create [TEMPLATE_NAME]"
        ;;
esac
