#!/bin/bash

SCRIPT_DIR="$( cd `dirname "${BASH_SOURCE[0]}"`/../.. && pwd )"
THIS=`basename $0`
silent=yes
source $SCRIPT_DIR/functions.sh

if ! is_installed $THIS; then
    echo "$TIME_NOW: it works!" >> /shared/tmp/it_works
    set_installed $THIS
fi
